### ISSUE TITLE
Wrong shared library versioning

### ISSUE THREAD

**Issue by bobhairgrove** [rgamble/libcsv#2]
Although I have installed version 3.0.3 of libcsv, the actual libraries are named like this:

```
bob@mylaptop:/usr/local/lib$ ls -l *csv*
-rw-r--r-- 1 root root 32272 Dec 12 21:38 libcsv.a
-rwxr-xr-x 1 root root   936 Dec 12 21:38 libcsv.la
lrwxrwxrwx 1 root root    15 Dec 12 21:38 libcsv.so -> libcsv.so.3.0.2
lrwxrwxrwx 1 root root    15 Dec 12 21:38 libcsv.so.3 -> libcsv.so.3.0.2
-rwxr-xr-x 1 root root 34224 Dec 12 21:38 libcsv.so.3.0.2
```

It looks like this might be the cause of that:

```
bob@mylaptop:~/libcsv-master$ grep -R version-info
(...)
Makefile.am:     libcsv_la_LDFLAGS = -version-info 3:2:0
```

Shouldn't this be 3:3:0?

**Comment by rgamble** [comment]
I'm not sure is this was an oversight or a misguided attempt at backwards compatibility since there were no API changes but in either case it should probably be changed.

**Comment by bobhairgrove** [comment]
I changed `3:2:0` in **Makefile.am** to `3:3:0` locally, ran `configure` again and rebuilt everything, and the `.so` file was versioned correctly (3.0.3).
